export const API = {
  usuarios: "usuarios",
  usLogin: "usuarios/login",
  usRegister: "usuarios/register",
  administradores: "administradores",
  consumidores: "consumidores",
  emociones: "emociones",
  motivos: "motivos",
  soluciones: "soluciones",
  habitos: "habitos",
  permisos: "permisos",
  formularios: "formularios",
  formulariosTemporales: "formularios-temporales",
  ventanas: "ventanas",
  lecturas: "lecturas",
  analisis: "analisis",
  deseos: "deseos",
  notificaciones: "notificaciones",

  dashboard: {
    habitTracking: "dashboard/habit-tracking",
    habitStats: "dashboard/habit-stats",
    heartRate: "dashboard/heart-rate",                
    heartRateStats: "dashboard/heart-rate-stats",
    predictionTimeline: "dashboard/prediction-timeline",
    predictionSummary: "dashboard/prediction-summary",
    desiresTracking: "dashboard/desires-tracking",
    desiresStats: "dashboard/desires-stats",
    dailySummary: "dashboard/daily-summary",
    weeklyComparison: "dashboard/weekly-comparison",  
    heartRateToday: "dashboard/heart-rate-today"
  },
};
